Fix default value for broker path (by getting rid of it).
It had a stray slash at the end which resulted in error:
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid path string "/brokers//topics/product.inventory_2/partitions" caused by empty node name specified @9